spring.application.name=HotelManagement-Assessment
# Server Port
server.port=9091


# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=capgdb
spring.datasource.password=capgdb
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect