spring.application.name=DematAccountService
server.port = 9093
eureka.instance.prefer-ip-address=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/demat_db
spring.datasource.username=root
spring.datasource.password=Amma@3023
